### ISSUE TITLE
issue with install.taxonerd()

### ISSUE THREAD

**Issue by julianflowers** [nleguillarme/taxonerd#9]
Hi

I keep getting this error message when I run import.taxonerd() - for whatever reason I can't install core python packages

m pip install --upgrade --no-user "pip" "wheel" "setuptools"
Error: Error installing package(s): "\"pip\"", "\"wheel\"", "\"setuptools\""

I am running Windows 11, RStudio2022.02.3 build 492 and V4.2 of R, on a machine with 128Gb RAM.

I also have a problem with nmslib installation

I'd love to be able to get taxonerd working in R

Any ideas?

Thanks

**Comment by nleguillarme** [comment]
Hi @julianflowers
Thank you for your interest in TaxoNERD.

Could you confirm that you installed TaxoNERD (using install.taxonerd) first ? I suppose you didn't, or couldn't, since it also requires having the core python packages.

In case you didn't run install.taxonerd, could you do it and send me the logs ?

**Comment by nleguillarme** [comment]
Could you please check if C:/Users/Julian/OneDrive/Documents/.virtualenvs/r-taxonerd/Scripts/python.exe actually exists ?

**Comment by nleguillarme** [comment]
I see in #10 that you managed to get things installed. Can I close this issue ?

**Comment by nleguillarme** [comment]
I close the issue. Feel free to reopen it if necessary.
